### ISSUE TITLE
eslint errors

### ISSUE THREAD

**Issue by iliran11** [unimonkiez/react-cordova-boilerplate#18]
hi,
Enviroment:
* **VS Code:** 1.10.2
* **react-cordova-boilerplate:** 2.0.0
* **vscode-eslint:**:  1.2.7
* **eslint:** 3.10.10

while using the latest version of `react-cordova-boilerplate` , out of the box without any changes, getting on VS Code the following errors:

```
Cannot read config file: c:\projects\banking-app-cordova-react\bin\webpack-eslint.js
Error: Could not locate the bindings file.
Tried: → c:\projects\banking-app-cordova-react\node_modules\deasync\build\deasync.node
→ c:\projects\banking-app-cordova-react\node_modules\deasync\build\Debug\deasync.node
→ c:\projects\banking-app-cordova-react\node_modules\deasync\build\Release\deasync.node
→ c:\projects\banking-app-cordova-react\node_modules\deasync\out\Debug\deasync.node → c:\projects\banking-
```

![image](https://cloud.githubusercontent.com/assets/24987188/24096277/b10d2800-0d69-11e7-8d7d-4eff926df3b0.png)

**Comment by unimonkiez** [comment]
Running the lints through command line throws an error too? 'npm run lint'

**Comment by iliran11** [comment]
if the jsx file is valid, it's running without error or any other feedback.
if the jsx is not valid, for example, changing the name of variable `Login` to `Logi`, it produce this behavior:

```
C:\projects\banking-app-cordova-react\src\containers\app-route.jsx
   7:8   error  'Logi' is defined but never used  no-unused-vars
  69:16  error  'Login' is not defined            react/jsx-no-undef
  75:41  error  'Login' is not defined            no-undef
  85:18  error  'Login' is not defined            no-undef
  86:25  error  'Login' is not defined            no-undef

✖ 5 problems (5 errors, 0 warnings)


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-cordova-boilerplate@2.0.1-alpha.3 lint: `eslint --fix --ext .js,.jsx .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-cordova-boilerplate@2.0.1-alpha.3 lint script 'eslint --fix --ext .js,.jsx .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-cordova-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --fix --ext .js,.jsx .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-cordova-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-cordova-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\banking-app-cordova-react\npm-debug.log
```

contents of npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle react-cordova-boilerplate@2.0.1-alpha.3~prelint: react-cordova-boilerplate@2.0.1-alpha.3
6 silly lifecycle react-cordova-boilerplate@2.0.1-alpha.3~prelint: no script for prelint, continuing
7 info lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: react-cordova-boilerplate@2.0.1-alpha.3
8 verbose lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: unsafe-perm in lifecycle true
9 verbose lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\projects\banking-app-cordova-react\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Ruby23-x64\bin;C:\Users\liranc\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\liranc\AppData\Local\atom\bin;C:\Users\liranc\AppData\Roaming\npm;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\liranc\AppData\Local\Android\sdk\tools;C:\Users\liranc\AppData\Local\Android\sdk\platform-tools
10 verbose lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: CWD: C:\projects\banking-app-cordova-react
11 silly lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: Args: [ '/d /s /c', 'eslint --fix --ext .js,.jsx .' ]
12 silly lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: Returned: code: 1  signal: null
13 info lifecycle react-cordova-boilerplate@2.0.1-alpha.3~lint: Failed to exec lint script
14 verbose stack Error: react-cordova-boilerplate@2.0.1-alpha.3 lint: `eslint --fix --ext .js,.jsx .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-cordova-boilerplate@2.0.1-alpha.3
16 verbose cwd C:\projects\banking-app-cordova-react
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
19 error node v7.3.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-cordova-boilerplate@2.0.1-alpha.3 lint: `eslint --fix --ext .js,.jsx .`
22 error Exit status 1
23 error Failed at the react-cordova-boilerplate@2.0.1-alpha.3 lint script 'eslint --fix --ext .js,.jsx .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-cordova-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     eslint --fix --ext .js,.jsx .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-cordova-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-cordova-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
