### ISSUE TITLE
Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by sam3k** [unimonkiez/react-cordova-boilerplate#29]
ERROR in ./~/css-loader!./~/resolve-url-loader?{"fail":true}!./~/sass-loader/lib/loader.js!./src/style/custom-font.scss
Module build failed: Error: Missing binding /Users/Me/Projects/my_app/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/Me/Projects/my_app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/Me/Projects/my_app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Me/Projects/my_app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./src/style/custom-font.scss 4:14-186 13:2-17:4 14:20-192
 @ ./src/containers/login.jsx
 @ ./src/containers/app-route.jsx
 @ ./src/entry-points/client.jsx
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/entry-points/client.jsx

ERROR in ./~/css-loader!./~/resolve-url-loader?{"fail":true}!./~/sass-loader/lib/loader.js!./src/style/todo-style.scss
Module build failed: Error: Missing binding /Users/Me/Projects/my_app/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/Me/Projects/my_app/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/Me/Projects/my_app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Me/Projects/my_app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
 @ ./src/style/todo-style.scss 4:14-185 13:2-17:4 14:20-191
 @ ./src/containers/todo-app.jsx
 @ ./src/containers/app-route.jsx
 @ ./src/entry-points/client.jsx
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/entry-points/client.jsx

**Comment by sam3k** [comment]
PR for adding a troubleshooting solution for this: https://github.com/unimonkiez/react-cordova-boilerplate/pull/28
